// A few left for reference - they are not correct.
enum EasterEggsSpecial_MW_A121
{
	EASTER_EGG_UNLOCK_ALL_THINGS = 0,
	EASTER_EGG_SKIP_DDAY = 1,
	EASTER_EGG_DISABLE_MIKE_MANN_BUILD = 2,
	EASTER_EGG_BURGER_KING = 3,
	EASTER_EGG_CASTROL = 4,
	EASTER_EGG_SPECIAL_LANGUAGES_TOGGLE = 5,
	EASTER_EGG_SPECIAL_XBOX_SAFEZONE = 6,
	EASTER_EGG_EREG2_200 = 7,
	EASTER_EGG_EREG2_VINYL = 8,
	EASTER_EGG_PREORDER = 9
};

enum EasterEggsType_MW_A121
{
	EASTER_EGG_CARS = 0,
	EASTER_EGG_VISUAL_PARTS = 1,
	EASTER_EGG_PERF_PARTS = 2,
	EASTER_EGG_DRIFT_PHYSICS = 3,
	EASTER_EGG_TRACK = 4,
	EASTER_EGG_SPECIAL = 5,
	EASTER_EGG_PRESETCARS = 6,
	EASTER_EGG_MANUFACTURER_VINYL = 7
};


enum EasterEggsItem_ProStreet
{
	EASTER_EGG_UNLOCK_ALL_THINGS = 0,
	EASTER_EGG_LEIPZIG = 1,
	EASTER_EGG_CASTROL_CASH = 2,
	EASTER_EGG_ENERGIZER_DECAL = 3,
	EASTER_EGG_ENERGIZER_CAR = 4,
	EASTER_EGG_PROGRESSIVE_CAR = 5,
	EASTER_EGG_K_N_DECAL = 6,
	EASTER_EGG_EA_MOBILE_CASH_1 = 7,
	EASTER_EGG_EA_MOBILE_CASH_2 = 8,
	EASTER_EGG_EA_MOBILE_CASH_3 = 9,
	EASTER_EGG_EA_MOBILE_CASH_4 = 10,
	EASTER_EGG_COKE_ZERO = 11,
	EASTER_EGG_EA_REGISTER = 12,
	EASTER_EGG_EXTRA_CASH = 13,
	EASTER_EGG_FREE_REPAIRS = 14,
	EASTER_EGG_EVO_UNLOCK = 15,
	EASTER_EGG_SUBARU = 16,
	EASTER_EGG_MAX = 17
};

enum EasterEggsType_ProStreet
{
	EASTER_EGG_GENERAL = 0,
	EASTER_EGG_CARS = 1,
	EASTER_EGG_VISUAL_PARTS = 2,
	EASTER_EGG_PERF_PARTS = 3,
	EASTER_EGG_DRIFT_PHYSICS = 4,
	EASTER_EGG_TRACK = 5,
	EASTER_EGG_SPECIAL = 6,
	EASTER_EGG_PRESETCARS = 7,
	EASTER_EGG_MANUFACTURER_VINYL = 8
};

enum EasterEggGroups_ProStreet
{
	EASTER_EGG_NO_GROUP = 0,
	EASTER_EGG_RENDERING_GROUP = 1,
	v = 2 // ? what
};

// New ones from Carbon - names derived from what little information I could find.

enum EasterEggsItem
{
	EASTER_EGG_UNKNOWN_0 = 0,
	EASTER_EGG_UNKNOWN_1 = 1,
	EASTER_EGG_UNKNOWN_2 = 2,
	EASTER_EGG_UNKNOWN_3 = 3,
	EASTER_EGG_UNKNOWN_4 = 4,
	EASTER_EGG_UNKNOWN_5 = 5,
	EASTER_EGG_UNKNOWN_6 = 6,
	EASTER_EGG_UNKNOWN_7 = 7,
	EASTER_EGG_UNKNOWN_8 = 8,
	EASTER_EGG_INFINITE_CREW_CHARGE = 9,
	EASTER_EGG_INFINITE_NOS = 10,
	EASTER_EGG_INFINITE_RACE_BREAKER = 11,
	EASTER_EGG_UNKNOWN_12 = 12, // Seems to be the Mazda Carlot
	EASTER_EGG_UNKNOWN_13 = 13,
	EASTER_EGG_UNKNOWN_14 = 14,
	EASTER_EGG_UNKNOWN_15 = 15,
	EASTER_EGG_UNKNOWN_16 = 16,
	
	// 17 and 18 seem to be referred by the game's code...
	// The table only has 17 entries though, so it should not refer to these. Perhaps leftovers of some kind?
	// TODO: Check if the debug build has more.
	
	EASTER_EGG_MAX = 17 
};