enum EVIEW_ID
{
    EVIEW_NONE = -1,
    EVIEW_FLAILER = 0,
    EVIEW_PLAYER1 = 1,
    EVIEW_PLAYER2 = 2,
    EVIEW_PLAYER1_RVM = 3,
    EVIEW_PLAYER1_REFLECTION = 4,
    EVIEW_PLAYER2_REFLECTION = 5,
    EVIEW_PLAYER1_GLOW = 6,
    EVIEW_PLAYER2_GLOW = 7,
    EVIEW_PLAYER1_PIP = 8,
    EVIEW_PLAYER1_SPECULAR = 9,
    EVIEW_PLAYER2_SPECULAR = 10,
    EVIEW_HEADLIGHT_P1 = 11,
    EVIEW_HEADLIGHT_P2 = 12,
    EVIEW_QUADRANT_TOP_LEFT = 13,
    EVIEW_QUADRANT_TOP_RIGHT = 14,
    EVIEW_QUADRANT_BOTTOM_LEFT = 15,
    EVIEW_QUADRANT_BOTTOM_RIGHT = 16,
    EVIEW_HDR_SCENE = 17,
    EVIEW_SHADOWMAP1 = 18,
    EVIEW_SHADOWMAP2 = 19,
    EVIEW_SHADOWMATTE = 20,
    EVIEW_ENVMAP0F = 21,
    EVIEW_ENVMAP0R = 22,
    EVIEW_ENVMAP0B = 23,
    EVIEW_ENVMAP0L = 24,
    EVIEW_ENVMAP0U = 25,
    EVIEW_ENVMAP0D = 26,

    EVIEW_FIRST = EVIEW_PLAYER1,
    EVIEW_LAST = EVIEW_ENVMAP0D,

    EVIEW_FIRST_RENDER = EVIEW_PLAYER1,
    EVIEW_LAST_RENDER = EVIEW_ENVMAP0D,

    EVIEW_FIRST_PLAYER = EVIEW_PLAYER1,
    EVIEW_LAST_PLAYER = EVIEW_PLAYER1_RVM,

    EVIEW_FIRST_RVM = EVIEW_PLAYER1_RVM,
    EVIEW_LAST_RVM = EVIEW_PLAYER1_RVM,

    EVIEW_FIRST_ENVMAP = EVIEW_ENVMAP0F,
    EVIEW_LAST_ENVMAP = EVIEW_ENVMAP0D,

    NUM_EVIEWS = 27,
    NUM_RENDER_VIEWS = 26,
    NUM_PLAYER_VIEWS = 3,
    NUM_RVM_VIEWS = 1,  
};

// TODO: Check if it matches?
// I can confirm that FILTER_TOTAL is 11, but that's all.
enum FILTER_ID
{
    FILTER_OFF = 0,
    FILTER_DEFAULT = 1,
    FILTER_EFB_XFB = 2,
    FILTER_CUBE_FACES = 3,
    FILTER_SPHERE_MAP = 4,
    FILTER_REFLECTION = 5,
    FILTER_MOTIONBLUR = 6,
    FILTER_GLOWBLOOM = 7,
    FILTER_CONTRAST_INTENSITY = 8,
    FILTER_EFB_XFB_AA = 9,
    FILTER_PIXELATE = 10,
    FILTER_TOTAL = 11,
};

enum TARGET_ID
{
    TARGET_FLAYER = 0,
    TARGET_PLAYER1 = 1,
    TARGET_PLAYER2 = 2,
    
    // maybe?
    // not referenced anywhere
    TARGET_PLAYER1_SPECULAR = 3,
    TARGET_PLAYER2_SPECULAR = 4,

    TARGET_PLAYER1_RVM = 5,
    TARGET_PLAYER1_REFLECTION = 6,
    TARGET_PLAYER2_REFLECTION = 7,
    TARGET_PLAYER1_GLOW = 8,
    TARGET_PLAYER2_GLOW = 9,

    TARGET_QUADRANT_TOP_LEFT = 10,
    TARGET_QUADRANT_TOP_RIGHT = 11,
    TARGET_QUADRANT_BOTTOM_LEFT = 12,
    TARGET_QUADRANT_BOTTOM_RIGHT = 13,

    TARGET_ENVMAP0F = 14,
    TARGET_ENVMAP0R = 15,
    TARGET_ENVMAP0B = 16,
    TARGET_ENVMAP0L = 17,
    TARGET_ENVMAP0U = 18,
    TARGET_ENVMAP0D = 19,
    TARGET_ENVMAP0_FULL = 20,

    TOTAL_RENDER_TARGETS = 21,

    FIRST_RENDER_TARGET = 0,
    LAST_RENDER_TARGET = 20,

    NUM_RENDER_TARGETS = 21,
};
